### ISSUE TITLE
Cant Uninstall the addon

### ISSUE THREAD

**Issue by djtail** [qJake/HADotNet.CommandCenter#106] opened 2020-10-10 00:43 UTC
## Description

Cant uninstall the addon using the supervisor gui

## Environment

Running Version 0.6.0

 Hass.io on a Raspberry Pi 3B+

## Steps to Reproduce

going true the supervisor gui, and press the uninstall button i got this fail message when trying to uninstall, checked the logs but they are empty

## Screenshots

<Paste or upload screenshots here.>
![bild](https://user-images.githubusercontent.com/71974961/95641385-4267a300-0aa2-11eb-9a7b-5b5e65ba5573.png)

**Comment by qJake** [comment] 2020-10-11 19:54
This is a known issue and a duplicate of #42 - please refer to that conversation.

This is fixed in 1.0+, will be releasing soon.

**Closed by qJake** 2020-10-11 19:54 UTC
Labels: bug
