### ISSUE TITLE
Larger tiles don't allow smaller tiles to stick to each other

### ISSUE THREAD

**Issue by davolesh** [qJake/HADotNet.CommandCenter#23] opened 2019-09-03 13:53 UTC
Hi, great application!! I'm having an issue where the small tiles cant stick to each other when there's a larger tile on the layout.

![image](https://user-images.githubusercontent.com/10506816/64179079-88c6e900-ce30-11e9-8b61-9a4e2bf6ad2b.png)

![image](https://user-images.githubusercontent.com/10506816/64179331-fe32b980-ce30-11e9-9612-1f189ecfcfd7.png)

**Comment by qJake** [comment] 2019-09-03 14:03
Thanks for reporting this issue! This is actually a duplicate of #18, you can work around this by making your first tile (upper left corner) a 1x1 tile, and pressing Save Layout. That will let you place them in the grid properly.

I am working on getting this fixed so you can put something else besides a 1x1 in the first spot.

Closing as a duplicate, please track #18 thanks!

**Closed by qJake** 2019-09-03 14:03 UTC

**Comment by davolesh** [comment] 2019-09-03 18:22
Thanks!
