### ISSUE TITLE
Impossible to save Theme settings

### ISSUE THREAD

**Issue by sr-as2** [qJake/HADotNet.CommandCenter#14] opened 2019-09-02 14:07 UTC
Hello,
i can't save theme setting. There is no error message. I can edit colors, types etc... I can save my modifications, but when i'm back to this menu, nothing has been saved.
Version 0.4.1
Regards

**Comment by bachoo786** [comment] 2019-09-04 18:07
@sr-as2 same here

**Comment by qJake** [comment] 2019-09-04 18:09
I will be adding additional logging and error messages to the next version of HACC.

In the meantime, can you check the Docker console output for the HACC container and tell me if you see any errors?

**Comment by bachoo786** [comment] 2019-09-04 18:14
No errors. I have posted my docker log in HA forum

**Comment by castanhinha1** [comment] 2019-09-04 20:48
Same issue. This is the only issue I am really getting. Connection id "0HLPGRP59BR7G", Request id "0HLPGRP59BR7G:00000005": An unhandled exception was thrown by the application.

**Comment by qJake** [comment] 2019-09-06 05:21
After some testing, I believe the issue is validation and just that the page doesn't tell you the validation errors. I'll be fixing that in a new version, in the meantime, please try **setting the following fields at a minimum** and then saving the theme:

* Background Color
* Font Size
* Tile BG Color
* Tile Font Color
* Tile Border Radius
* Default On Color
* Default Off Color

Let me know if this works!

**Comment by qJake** [comment] 2019-09-07 16:28
This will be fixed in 0.5.0, releasing this weekend sometime!

**Comment by qJake** [comment] 2019-09-08 06:41
Released: https://github.com/qJake/HADotNet.CommandCenter/releases/tag/v0.5.0

**Closed by qJake** 2019-09-08 06:41 UTC
Labels: bug
